'use client';

import React, { useEffect, useState } from 'react';
import { useDebugStore } from '@/lib/store/debug';
import { useFilesStore } from '@/lib/store/files';
import {
	Sheet,
	SheetContent,
	SheetHeader,
	SheetTitle,
} from '@/components/ui/shadcn/sheet';
import type { ErrorCapture, DebugFix } from '@/types/debug';
import { DiffEditor } from '@monaco-editor/react';

function extToLanguage(path?: string): string | undefined {
	if (!path) return undefined;
	if (path.endsWith('.ts')) return 'typescript';
	if (path.endsWith('.tsx')) return 'typescript';
	if (path.endsWith('.js')) return 'javascript';
	if (path.endsWith('.jsx')) return 'javascript';
	if (path.endsWith('.css')) return 'css';
	if (path.endsWith('.json')) return 'json';
	if (path.endsWith('.md')) return 'markdown';
	if (path.endsWith('.html')) return 'html';
	return undefined;
}

function ModelBadge({ model }: { model: 'grok' | 'claude' }) {
	return (
		<span
			className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium"
			aria-label={`Generated by ${model === 'grok' ? 'Grok' : 'Claude'}`}
		>
			{model === 'grok' ? (
				<span className="bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-200">
					Grok
				</span>
			) : (
				<span className="bg-orange-100 text-orange-800 dark:bg-orange-900 dark:text-orange-200">
					Claude
				</span>
			)}
		</span>
	);
}

function ApplyDiffModal({
	before,
	after,
	path,
	onApply,
	onCancel,
}: {
	before: string;
	after: string;
	path: string;
	onApply: () => void;
	onCancel: () => void;
}) {
	return (
		<div
			className="fixed inset-0 z-[100] flex items-center justify-center"
			role="dialog"
			aria-modal="true"
			aria-labelledby="apply-diff-title"
		>
			<div
				className="absolute inset-0 bg-black/30 dark:bg-black/50"
				onClick={onCancel}
				aria-hidden="true"
			/>
			<div className="relative bg-white dark:bg-zinc-950 rounded-lg shadow-xl w-[95vw] max-w-6xl max-h-[85vh] overflow-hidden border border-gray-200 dark:border-zinc-800">
				<div className="px-4 py-3 border-b border-gray-200 dark:border-zinc-800 flex items-center justify-between bg-gray-50 dark:bg-zinc-900">
					<div
						id="apply-diff-title"
						className="text-sm font-semibold text-gray-900 dark:text-zinc-50"
					>
						Review changes: {path}
					</div>
					<div className="flex items-center gap-2">
						<button
							onClick={onCancel}
							className="text-sm px-3 py-1 rounded-md border border-gray-200 dark:border-zinc-700 text-gray-700 dark:text-zinc-300 hover:bg-gray-50 dark:hover:bg-zinc-800 transition-colors"
							aria-label="Cancel applying changes"
						>
							Cancel
						</button>
						<button
							onClick={onApply}
							className="text-sm px-3 py-1 rounded-md bg-gray-900 dark:bg-zinc-50 text-white dark:text-zinc-900 hover:bg-gray-800 dark:hover:bg-zinc-200 transition-colors"
							aria-label="Apply changes to file"
						>
							Apply
						</button>
					</div>
				</div>
				<div className="h-[calc(85vh-60px)]">
					<DiffEditor
						height="100%"
						language={extToLanguage(applyDiff.path) || 'typescript'}
						theme="vs-dark"
						original={before}
						modified={after}
						options={{
							readOnly: true,
							renderSideBySide: true,
							ignoreTrimWhitespace: false,
							renderIndicators: true,
							enableSplitViewResizing: true,
						}}
					/>
				</div>
			</div>
		</div>
	);
}

export default function DebugModal() {
	const { activeError, fixes, setActiveError, clear } = useDebugStore();
	const { files, setStagedChanges } = useFilesStore();
	const [isOpen, setIsOpen] = useState(false);
	const [applyDiff, setApplyDiff] = useState<{
		before: string;
		after: string;
		path: string;
	} | null>(null);
	const [isApplying, setIsApplying] = useState(false);

	// Listen for 'sandbox-error' event
	useEffect(() => {
		const handleSandboxError = (event: CustomEvent<ErrorCapture>) => {
			const error = event.detail;
			setActiveError(error);
			setIsOpen(true);
		};

		window.addEventListener(
			'sandbox-error',
			handleSandboxError as EventListener,
		);

		return () => {
			window.removeEventListener(
				'sandbox-error',
				handleSandboxError as EventListener,
			);
		};
	}, [setActiveError]);

	// Update open state when activeError changes
	useEffect(() => {
		setIsOpen(!!activeError);
	}, [activeError]);

	const handleClose = () => {
		setIsOpen(false);
		clear();
	};

	const handleApply = async (fix: DebugFix) => {
		try {
			setIsApplying(true);
			
			// Call API for validation/logging
			const response = await fetch('/api/apply-debug', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({ fixId: fix.id }),
			});

			if (!response.ok) {
				throw new Error('Failed to apply fix');
			}

			// Use fix data directly to compute diff
			const before = files[fix.diff.path] || '';
			const after = applyUnifiedDiff(before, fix.diff.delta);

			// Show Monaco diff modal
			setApplyDiff({
				before,
				after,
				path: fix.diff.path,
			});
		} catch (error) {
			console.error('Failed to apply fix:', error);
		} finally {
			setIsApplying(false);
		}
	};

	const handleConfirmApply = () => {
		if (applyDiff) {
			setStagedChanges([
				{
					path: applyDiff.path,
					before: applyDiff.before,
					after: applyDiff.after,
					modelUsed: fixes.find((f) => f.diff.path === applyDiff.path)
						?.modelUsed || 'grok',
				},
			]);
			setApplyDiff(null);
			handleClose();
		}
	};

	// Simple unified diff application
	function applyUnifiedDiff(before: string, unified: string): string {
		const lines = unified
			.split('\n')
			.filter(
				(l) =>
					!l.startsWith('--- ') &&
					!l.startsWith('+++ ') &&
					!l.startsWith('@@'),
			);
		const beforeLines = before.split('\n');
		const out: string[] = [];
		let i = 0;
		for (const l of lines) {
			if (l.startsWith(' ')) {
				const expect = l.slice(1);
				if (beforeLines[i] === expect) {
					out.push(expect);
					i++;
				} else {
					return before;
				}
			} else if (l.startsWith('-')) {
				const rem = l.slice(1);
				if (beforeLines[i] === rem) {
					i++;
				}
			} else if (l.startsWith('+')) {
				out.push(l.slice(1));
			}
		}
		while (i < beforeLines.length) {
			out.push(beforeLines[i++]);
		}
		return out.join('\n');
	}

	if (!activeError) {
		return null;
	}

	return (
		<>
			<Sheet open={isOpen} onOpenChange={setIsOpen}>
				<SheetContent
					side="right"
					className="w-full sm:max-w-lg overflow-y-auto"
					aria-label="Debug error modal"
				>
					<SheetHeader>
						<SheetTitle className="text-lg font-semibold text-gray-900 dark:text-zinc-50">
							Debug: {activeError.message}
						</SheetTitle>
					</SheetHeader>

					<div className="mt-6 space-y-4">
						{fixes.length === 0 ? (
							<div className="text-sm text-gray-600 dark:text-zinc-400">
								No fixes available for this error.
							</div>
						) : (
							fixes.map((fix) => (
								<div
									key={fix.id}
									className="border border-gray-200 dark:border-zinc-800 rounded-lg p-4 bg-white dark:bg-zinc-900 shadow-sm"
									role="article"
									aria-labelledby={`fix-${fix.id}-title`}
								>
									<div className="flex items-start justify-between mb-3">
										<div className="flex-1">
											<h3
												id={`fix-${fix.id}-title`}
												className="text-sm font-medium text-gray-900 dark:text-zinc-50 mb-1"
											>
												Fix #{fix.id}
											</h3>
											<ModelBadge model={fix.modelUsed} />
										</div>
									</div>

									<div className="mb-3">
										<p className="text-sm text-gray-700 dark:text-zinc-300 whitespace-pre-wrap">
											{fix.explanation}
										</p>
									</div>

									{fix.tradeoffs && fix.tradeoffs.length > 0 && (
										<div className="mb-3">
											<h4 className="text-xs font-medium text-gray-600 dark:text-zinc-400 mb-2">
												Tradeoffs:
											</h4>
											<ul className="list-disc list-inside space-y-1 text-xs text-gray-600 dark:text-zinc-400">
												{fix.tradeoffs.map((tradeoff, idx) => (
													<li key={idx}>{tradeoff}</li>
												))}
											</ul>
										</div>
									)}

									<button
										onClick={() => handleApply(fix)}
										disabled={isApplying}
										className="w-full mt-3 px-3 py-2 text-sm font-medium rounded-md bg-gray-900 dark:bg-zinc-50 text-white dark:text-zinc-900 hover:bg-gray-800 dark:hover:bg-zinc-200 disabled:opacity-50 disabled:cursor-not-allowed transition-colors flex items-center justify-center gap-2"
										aria-label={`Apply fix ${fix.id}`}
									>
										{isApplying ? (
											<>
												<span className="animate-spin">⏳</span>
												Applying...
											</>
										) : (
											<>
												Apply <ModelBadge model={fix.modelUsed} />
											</>
										)}
									</button>
								</div>
							))
						)}
					</div>
				</SheetContent>
			</Sheet>

			{applyDiff && (
				<ApplyDiffModal
					before={applyDiff.before}
					after={applyDiff.after}
					path={applyDiff.path}
					onApply={handleConfirmApply}
					onCancel={() => setApplyDiff(null)}
				/>
			)}
		</>
	);
}

